# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-07 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_voterdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterdetail',
            name='voter_id',
            field=models.IntegerField(),
        ),
    ]
