# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-07 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190407_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterdetail',
            name='voter_id',
            field=models.CharField(max_length=10),
        ),
    ]
