# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-07 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190407_1441'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoterDetail',
        ),
    ]
