# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-07 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_delete_voterdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(max_length=20)),
                ('voted', models.BooleanField(default=False)),
            ],
        ),
    ]
